pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/deployment']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/tmarkesic/Auction-App.git']]])
                sh "ls -lart ./*"
            }
        }


	    stage('Build and push backend') {
	        steps {
		        dir('./auctionapp') {
		             withCredentials([string(credentialsId: 'AWS_ACCESS_ID', variable: 'AWS_ACCESS_KEY'), string(credentialsId: 'AWS_SECRET_ID', variable: 'AWS_SECRET_KEY')]) {			    
		                sh 'docker run --rm -d -p 5432:5432 --name auction-db tmarkesic/auction-db'
                    		sh 'docker build -f ../deployment/Dockerfile_BE --build-arg aws_access_key=${AWS_ACCESS_KEY} --build-arg aws_secret_key=${AWS_SECRET_KEY} -t tmarkesic/auction-be .'
				sh 'docker rm -f auction-db'
				sh 'docker push tmarkesic/auction-be'

		            }
		        }
	        }
	    }

        stage('Build and push frontend') {
            steps {
                    dir('./frontend') {
                        	sh 'docker build -f ../deployment/Dockerfile_FE -t tmarkesic/auction-fe .'
    				sh 'docker push tmarkesic/auction-fe'
                }
             }
        }  
    }
}
